name: API Server CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, closed]
    branches: [main, master]

permissions:
  contents: read

jobs:
  build_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t api_server ./api_server

    - name: Run Docker Container
      run: |
        docker run --name api-server-test -d -p 5000:5000 --name api_server

    - name: Clean up
      run: docker stop api-server-test && docker rm api-server-test


